language: r
sudo: required
cache: packages

r_github_packages:
- jimhester/covr

env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes"
     - R_CHECK_ARGS="--no-build-vignettes --as-cran"

r_check_args: 
"--no-vignettes"
